server:
  port: 8081

spring:
  application:
    name: code-generator
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
  main:
    allow-bean-definition-overriding: true

mybatis:
  typeAliasesPackage: com.sekift.www.model
  mapperLocations: classpath:mapper/*.xml
  configuration:
    # 数据库中下划线自动转为驼峰
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    #输出sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

swagger:
  enabled: true
  host:
